# VisionInspect — 03 Train YOLO Segmentation

Baseline YOLO instance-segmentation training for the three prepared industrial inspection datasets:

- DAGM
- KolektorSDD2
- Magnetic Tile

Each dataset remains a **separate experiment** because their class semantics and visual domains differ.

### Objectives
1. Validate the generated dataset YAML files.
2. Train one reproducible YOLO segmentation baseline per dataset.
3. Track configuration, metrics and artifacts with MLflow.
4. Evaluate the selected model on the held-out test set.
5. Produce a compact baseline comparison for the portfolio.

This notebook intentionally avoids hyperparameter sweeps. Establish the baseline first; optimize later.

In [1]:
# Install once if needed:
# %pip install -U ultralytics mlflow pyyaml pandas matplotlib

from pathlib import Path
import platform
import subprocess
import time

import pandas as pd
import yaml
import mlflow
from ultralytics import YOLO

SEED = 42

DATA_ROOT = Path("datasets")
YOLO_ROOT = DATA_ROOT / "yolo_segmentation"
MLFLOW_DIR = Path("mlruns")
RUNS_DIR = Path("runs") / "segment"

PROJECT_NAME = "VisionInspect"

DATASETS = {
    "DAGM": YOLO_ROOT / "DAGM" / "dataset.yaml",
    "KolektorSDD2": YOLO_ROOT / "KolektorSDD2" / "dataset.yaml",
    "Magnetic_Tile": YOLO_ROOT / "Magnetic_Tile" / "dataset.yaml",
}

# Baseline model. Change deliberately, not during comparison.
MODEL_NAME = "yolo26n-seg.pt"

EPOCHS = 100
IMAGE_SIZE = 640
BATCH_SIZE = 16
WORKERS = 4
DEVICE = None  # None=Ultralytics auto; 0=first CUDA GPU; "cpu"=CPU

print("Dataset root:", DATA_ROOT.resolve())
print("YOLO root:", YOLO_ROOT.resolve())
print("Model:", MODEL_NAME)

/home/zubair/AI Development Directory/anomaly-detection/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Creating new Ultralytics Settings v0.0.7 file ✅
View Ultralytics Settings with 'yolo settings' or at '/home/zubair/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Dataset root: /home/zubair/AI Development Directory/anomaly-detection/datasets
YOLO root: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation
Model: yolo26n-seg.pt

## 1. Dataset YAML validation

The notebook expects the three generated YAML files at:

```text
datasets/yolo_segmentation/
├── DAGM/dataset.yaml
├── KolektorSDD2/dataset.yaml
└── Magnetic_Tile/dataset.yaml
```

Empty label files are valid: they represent normal images with no annotated defect.

In [2]:
def load_dataset_yaml(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Missing dataset YAML: {path}")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def resolve_dataset_root(yaml_path, cfg):
    root = Path(cfg["path"])
    return root if root.is_absolute() else (Path(yaml_path).parent / root).resolve()

dataset_info = {}

for name, yaml_path in DATASETS.items():
    cfg = load_dataset_yaml(yaml_path)
    root = resolve_dataset_root(yaml_path, cfg)
    dataset_info[name] = {"yaml": yaml_path, "config": cfg, "root": root}

    print(f"\n{name}")
    print("root   :", root)
    print("names  :", cfg.get("names"))
    print("train  :", cfg.get("train"))
    print("val    :", cfg.get("val"))
    print("test   :", cfg.get("test"))

DAGM
root   : /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/DAGM
names  : {0: 'Class1', 1: 'Class2', 2: 'Class3', 3: 'Class4', 4: 'Class5', 5: 'Class6', 6: 'Class7', 7: 'Class8', 8: 'Class9', 9: 'Class10'}
train  : images/train
val    : images/val
test   : images/test

KolektorSDD2
root   : /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/KolektorSDD2
names  : {0: 'defect'}
train  : images/train
val    : images/val
test   : images/test

Magnetic_Tile
root   : /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile
names  : {0: 'Blowhole', 1: 'Break', 2: 'Crack', 3: 'Fray', 4: 'Uneven'}
train  : images/train
val    : images/val
test   : images/test

## 2. Dataset integrity checks

In [3]:
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}

def inspect_split(root, split):
    image_dir = root / "images" / split
    label_dir = root / "labels" / split

    if not image_dir.exists():
        return {"split": split, "images": 0, "labels": 0,
                "missing_labels": 0, "empty_labels": 0}

    images = [p for p in image_dir.iterdir()
              if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS]
    labels = {p.stem: p for p in label_dir.glob("*.txt")} if label_dir.exists() else {}

    missing = 0
    empty = 0
    for image in images:
        label = labels.get(image.stem)
        if label is None:
            missing += 1
        elif not label.read_text(encoding="utf-8").strip():
            empty += 1

    return {"split": split, "images": len(images), "labels": len(labels),
            "missing_labels": missing, "empty_labels": empty}

rows = []
for name, info in dataset_info.items():
    for split in ["train", "val", "test"]:
        r = inspect_split(info["root"], split)
        r["dataset"] = name
        rows.append(r)

integrity_df = pd.DataFrame(rows)[
    ["dataset", "split", "images", "labels", "missing_labels", "empty_labels"]
]
display(integrity_df)

         dataset  split  images  labels  missing_labels  empty_labels
0           DAGM  train    1725    1725               0          1478
1           DAGM    val     911     911               0           793
2           DAGM   test    1150    1150               0          1000
3   KolektorSDD2  train    2332    2332               0          2086
4   KolektorSDD2    val       0       0               0             0
5   KolektorSDD2   test    1004    1004               0           894
6  Magnetic_Tile  train     940     940               0           669
7  Magnetic_Tile    val       0       0               0             0
8  Magnetic_Tile   test     404     404               0           287

## 3. MLflow setup

MLflow is used for experiment tracking. It is deliberately separate from serving.

Each dataset receives its own experiment:

```text
VisionInspect_DAGM
VisionInspect_KolektorSDD2
VisionInspect_Magnetic_Tile
```

In [8]:
import os

os.environ["MLFLOW_ALLOW_FILE_STORE"] = "true"
mlflow.set_tracking_uri("sqlite:///mlflow.db")

for dataset_name in DATASETS:
    mlflow.set_experiment(f"{PROJECT_NAME}_{dataset_name}")

print("MLflow tracking URI:", mlflow.get_tracking_uri())

2026/08/11 21:27:07 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/08/11 21:27:07 INFO mlflow.store.db.utils: Updating database tables
2026/08/11 21:27:10 INFO mlflow.tracking.fluent: Experiment with name 'VisionInspect_DAGM' does not exist. Creating a new experiment.
2026/08/11 21:27:10 INFO mlflow.tracking.fluent: Experiment with name 'VisionInspect_KolektorSDD2' does not exist. Creating a new experiment.
2026/08/11 21:27:10 INFO mlflow.tracking.fluent: Experiment with name 'VisionInspect_Magnetic_Tile' does not exist. Creating a new experiment.

MLflow tracking URI: sqlite:///mlflow.db

## 4. Reproducibility / environment metadata

In [13]:
def git_commit():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL, text=True
        ).strip()
    except Exception:
        return "not_available"

ENVIRONMENT = {
    "python": platform.python_version(),
    "platform": platform.platform(),
    "git_commit": git_commit(),
}

try:
    import torch
    ENVIRONMENT["torch"] = torch.__version__
    ENVIRONMENT["cuda_available"] = str(torch.cuda.is_available())
    ENVIRONMENT["cuda_devices"] = str(torch.cuda.device_count())
    if torch.cuda.is_available():
        ENVIRONMENT["gpu"] = torch.cuda.get_device_name(0)
except Exception as exc:
    ENVIRONMENT["torch"] = f"unavailable: {exc}"

ENVIRONMENT

{'python': '3.14.4',
 'platform': 'Linux-7.0.0-29-generic-x86_64-with-glibc2.43',
 'git_commit': 'not_available',
 'torch': '2.13.0+cu130',
 'cuda_available': 'True',
 'cuda_devices': '1',
 'gpu': 'NVIDIA GeForce RTX 5070 Laptop GPU'}

## 5. Baseline configuration

Keep this fixed across the three datasets so the comparison is meaningful.

The important rule is: **baseline first, tuning second**.

In [14]:
TRAIN_CONFIG = {
    "epochs": EPOCHS,
    "imgsz": IMAGE_SIZE,
    "batch": BATCH_SIZE,
    "workers": WORKERS,
    "seed": SEED,
    "patience": 20,
    "optimizer": "auto",
    "pretrained": True,
    "plots": True,
    "verbose": True,
}

TRAIN_CONFIG

{'epochs': 100,
 'imgsz': 640,
 'batch': 16,
 'workers': 4,
 'seed': 42,
 'patience': 20,
 'optimizer': 'auto',
 'pretrained': True,
 'plots': True,
 'verbose': True}

## 6. Metric extraction

In [10]:
def as_float(value):
    try:
        return float(value)
    except Exception:
        return None

def extract_metrics(metrics):
    out = {}

    if hasattr(metrics, "box"):
        for key, attr in [
            ("precision", "mp"),
            ("recall", "mr"),
            ("map50", "map50"),
            ("map50_95", "map"),
        ]:
            value = getattr(metrics.box, attr, None)
            if value is not None:
                out[f"box_{key}"] = as_float(value)

    if hasattr(metrics, "seg"):
        for key, attr in [
            ("precision", "mp"),
            ("recall", "mr"),
            ("map50", "map50"),
            ("map50_95", "map"),
        ]:
            value = getattr(metrics.seg, attr, None)
            if value is not None:
                out[f"seg_{key}"] = as_float(value)

    return out

## 7. Train one dataset

The function trains the model, logs parameters and environment metadata to MLflow, evaluates validation performance, and logs the native Ultralytics artifacts.

The test set is **not** used here.

In [11]:
def train_dataset(dataset_name):
    yaml_path = DATASETS[dataset_name]
    experiment_name = f"{PROJECT_NAME}_{dataset_name}"

    experiment = mlflow.get_experiment_by_name(experiment_name)
    if experiment is None:
        mlflow.set_experiment(experiment_name)
        experiment = mlflow.get_experiment_by_name(experiment_name)

    with mlflow.start_run(
        experiment_id=experiment.experiment_id,
        run_name=f"{dataset_name}_baseline",
    ) as run:

        cfg = dataset_info[dataset_name]["config"]

        mlflow.log_params({
            "model": MODEL_NAME,
            "dataset": dataset_name,
            "epochs": EPOCHS,
            "imgsz": IMAGE_SIZE,
            "batch": BATCH_SIZE,
            "workers": WORKERS,
            "seed": SEED,
            "patience": TRAIN_CONFIG["patience"],
        })
        mlflow.log_dict(cfg, "dataset.yaml")
        mlflow.log_dict(ENVIRONMENT, "environment.json")

        model = YOLO(MODEL_NAME)
        start = time.time()

        model.train(
            data=str(yaml_path),
            project=str(RUNS_DIR),
            name=dataset_name.lower(),
            exist_ok=True,
            device=DEVICE,
            **TRAIN_CONFIG,
        )

        train_seconds = time.time() - start
        mlflow.log_metric("training_seconds", train_seconds)

        best_model = Path(model.trainer.best)
        last_model = Path(model.trainer.last)
        native_dir = Path(model.trainer.save_dir)

        for path in [best_model, last_model]:
            if path.exists():
                mlflow.log_artifact(str(path), artifact_path="model")

        if native_dir.exists():
            mlflow.log_artifacts(str(native_dir), artifact_path="ultralytics_run")

        val = model.val(
            data=str(yaml_path),
            split="val",
            imgsz=IMAGE_SIZE,
            batch=BATCH_SIZE,
            device=DEVICE,
            plots=True,
        )

        val_metrics = extract_metrics(val)
        if val_metrics:
            mlflow.log_metrics({
                f"val_{k}": v for k, v in val_metrics.items()
                if v is not None
            })

        mlflow.set_tags({
            "project": PROJECT_NAME,
            "dataset": dataset_name,
            "task": "instance_segmentation",
            "stage": "baseline",
        })

        return {
            "run_id": run.info.run_id,
            "best_model": str(best_model),
            "last_model": str(last_model),
            "native_run_dir": str(native_dir),
            "training_seconds": train_seconds,
            "val_metrics": val_metrics,
        }

## 8. Run the first baseline

Start with **Magnetic Tile** because it is small and gives the fastest end-to-end validation.

If this completes successfully, run KolektorSDD2 and DAGM.

In [16]:
# Uncomment to run:

baseline_results = {}
baseline_results["Magnetic_Tile"] = train_dataset("Magnetic_Tile")
baseline_results["Magnetic_Tile"]["val_metrics"]

Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Laptop GPU, 7708MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=datasets/yolo_segmentation/Magnetic_Tile/dataset.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=magnetic_tile, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs/segment, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    792251  ultralytics.nn.modules.head.Segment26        [5, 32, 64, 1, True, [64, 128, 256]]
YOLO26n-seg summary: 309 layers, 3,054,875 parameters, 3,054,875 gradients, 10.3 GFLOPs

Transferred 740/844 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1501.0±2718.6 MB/s, size: 41.4 KB)
train: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile/labels/train... 940 images, 669 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 940/940 5.7Kit/s 0.2s0.2s
train: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile/labels/train.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1815.7±1948.0 MB/s, size: 39.9 KB)
val: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile/labels/val... 202 images, 143 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 202/202 3.7Kit/s 0.1s
val: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 134 weight(decay=0.0), 154 weight(decay=0.0005), 154 bias(decay=0.0)
Plotting labels to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/labels.jpg...

2026/08/11 21:33:51 INFO mlflow.tracking.fluent: Experiment with name 'runs/segment' does not exist. Creating a new experiment.

MLflow: logging run_id(e271a4c46c944511a58c8d92875f6944) to sqlite:///mlflow.db
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      1/100      3.16G      1.496      3.361      22.95    0.01131      8.381          8        640: 100% ━━━━━━━━━━━━ 59/59 4.5it/s 13.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.7it/s 4.2s0.7ss
                   all        202         78   0.000678      0.314     0.0606     0.0298   0.000758      0.389     0.0639     0.0307

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      2/100      3.18G      1.516      2.656       18.9    0.01148      4.998          3        640: 100% ━━━━━━━━━━━━ 59/59 7.6it/s 7.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 9.6it/s 0.7s0.1s
                   all        202         78      0.714      0.139      0.156     0.0807      0.714      0.139      0.141     0.0585

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      3/100      3.19G       1.63      2.572      14.17    0.01345      2.637          6        640: 100% ━━━━━━━━━━━━ 59/59 7.7it/s 7.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 9.4it/s 0.7s0.1s
                   all        202         78      0.638      0.201      0.174      0.101      0.649      0.221      0.196     0.0909

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      4/100      3.17G      1.767      2.583      10.39    0.01466      1.713         11        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 9.6it/s 0.7s0.1s
                   all        202         78      0.923      0.135      0.221        0.1      0.693      0.176      0.222       0.09

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      5/100      3.19G      1.751      2.409      8.058    0.01439      1.587         10        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.0it/s 0.7s.3s
                   all        202         78      0.691      0.181      0.254     0.0977      0.433      0.209      0.238      0.074

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      6/100      3.17G      1.729      2.332      6.531    0.01542      1.326          7        640: 100% ━━━━━━━━━━━━ 59/59 7.7it/s 7.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.1it/s 0.7s.1s
                   all        202         78      0.515      0.301      0.303      0.129      0.507      0.295      0.295      0.109

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      7/100      3.18G       1.83      2.523      5.125    0.01503      0.928         23        640: 100% ━━━━━━━━━━━━ 59/59 7.7it/s 7.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.2it/s 0.7s.3s
                   all        202         78      0.488      0.341      0.342      0.162      0.488      0.341      0.343      0.154

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      8/100      3.19G      1.781      2.327      4.358    0.01401      0.725         11        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.3it/s 0.7s.3s
                   all        202         78      0.226      0.368      0.273      0.119      0.444      0.368       0.28      0.127

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      9/100      3.17G      1.705      2.363      3.618    0.01473     0.5481          3        640: 100% ━━━━━━━━━━━━ 59/59 7.7it/s 7.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.7it/s 0.7s.3s
                   all        202         78      0.354      0.386      0.356      0.173      0.338      0.349      0.341      0.142

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     10/100      3.17G      1.755      2.363      3.301    0.01455     0.4363         12        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.6s.3s
                   all        202         78      0.448      0.381      0.389      0.189      0.432      0.371      0.376      0.185

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     11/100      3.17G      1.709      2.291      2.805    0.01392     0.4416         14        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.6it/s 0.7s.3s
                   all        202         78       0.52      0.399      0.456      0.236      0.494      0.369      0.436      0.208

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     12/100      3.17G      1.716       2.02      2.661    0.01493     0.4151          7        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.5it/s 0.7s.3s
                   all        202         78      0.591      0.499      0.472      0.245      0.569      0.487      0.459      0.215

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     13/100      3.17G      1.639      2.095      2.563    0.01485     0.4154          8        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.7it/s 0.7s.3s
                   all        202         78      0.531       0.43      0.471       0.25      0.559      0.414      0.458      0.208

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     14/100      3.17G      1.665      2.153      2.313    0.01429     0.3483          9        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.6s.3s
                   all        202         78      0.603       0.53      0.549      0.284      0.492      0.566      0.556      0.269

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     15/100      3.17G      1.573      2.009       2.05    0.01313     0.3608          4        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.4it/s 0.7s.1s
                   all        202         78      0.508      0.504       0.48      0.251      0.554      0.472      0.498      0.228

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     16/100      3.17G      1.629      2.063      1.967    0.01302     0.3594          7        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.6it/s 0.7s.3s
                   all        202         78      0.551      0.529      0.538      0.285      0.557      0.535      0.539      0.253

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     17/100      3.19G      1.691      2.144      2.086     0.0135     0.3167         13        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s
                   all        202         78      0.597       0.52      0.558      0.276      0.603       0.49      0.565      0.252

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     18/100      3.17G      1.669      1.888      1.972    0.01448     0.3751          5        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s
                   all        202         78      0.453      0.543      0.551      0.264      0.531      0.563      0.591      0.287

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     19/100      3.17G      1.618      1.876      1.755    0.01425     0.3247          9        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.6s.3s
                   all        202         78      0.706      0.536      0.619      0.268       0.59      0.566      0.605      0.281

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     20/100      3.17G      1.631      2.078      1.931    0.01307     0.3336          7        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.6s.3s
                   all        202         78      0.658      0.561      0.582      0.282       0.67      0.573      0.592      0.272

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     21/100      3.18G      1.547        1.9      1.746    0.01289     0.3427          8        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.6it/s 0.7s.3s
                   all        202         78      0.609      0.557      0.584      0.318      0.579      0.533       0.56      0.274

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     22/100      3.17G       1.52      2.066      1.664    0.01213     0.3436          8        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 11.0it/s 0.6s.3s
                   all        202         78       0.45      0.614       0.58      0.285      0.462      0.624      0.562      0.242

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     23/100      3.19G      1.507      1.852      1.551    0.01296     0.3064         12        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.6s.3s
                   all        202         78      0.691      0.577      0.599      0.291      0.626      0.523      0.534      0.233

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     24/100      3.17G      1.555      1.875      1.604    0.01134      0.312         14        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s
                   all        202         78      0.702      0.533      0.618      0.321      0.703      0.576      0.637       0.32

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     25/100      3.17G      1.542      2.018      1.558    0.01061     0.3166          6        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.6s.3s
                   all        202         78      0.662      0.613      0.656      0.375      0.616      0.647      0.651      0.343

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     26/100      3.18G      1.471      1.864      1.488    0.01113     0.3164          9        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s
                   all        202         78      0.715      0.611       0.71      0.351      0.688      0.631      0.701       0.33

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     27/100      3.17G       1.48      1.756      1.391     0.0119     0.3154          7        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s
                   all        202         78      0.639      0.647      0.671      0.371      0.719      0.687      0.707      0.336

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     28/100      3.18G      1.434      1.698      1.359     0.0101     0.2786          6        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.5it/s 0.7s.3s
                   all        202         78      0.668      0.577      0.599      0.342      0.641      0.544      0.581      0.275

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     29/100      3.17G      1.414      1.887      1.349    0.01056     0.2854          9        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s
                   all        202         78        0.7      0.618      0.683      0.407      0.716      0.634      0.699      0.346

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     30/100      3.17G      1.454      1.791      1.331    0.01157     0.3143         11        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.6it/s 0.7s.3s
                   all        202         78      0.766      0.617      0.718      0.405      0.749      0.599      0.697       0.35

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     31/100      3.19G      1.495      1.711      1.372    0.01263     0.2698          9        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 11.0it/s 0.6s.3s
                   all        202         78       0.76      0.634      0.696      0.432       0.76      0.634      0.685      0.341

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     32/100      3.17G      1.401      1.754      1.266    0.01176     0.2959          6        640: 100% ━━━━━━━━━━━━ 59/59 8.0it/s 7.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.7s.3s
                   all        202         78      0.726      0.621      0.697      0.416      0.726      0.621      0.695      0.337

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     33/100      3.17G      1.413      1.816      1.372    0.01075     0.2668         10        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.8it/s 0.7s.3s
                   all        202         78      0.783      0.638      0.721      0.428      0.784      0.654      0.732      0.382

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     34/100      3.17G       1.43      1.844      1.257    0.01128     0.2849         11        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.3it/s 0.7s.1s
                   all        202         78       0.89      0.666      0.772      0.462      0.848      0.641      0.716      0.371

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     35/100      3.17G      1.382      1.763      1.186    0.01074      0.279          9        640: 100% ━━━━━━━━━━━━ 59/59 7.8it/s 7.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 11.0it/s 0.6s.3s
                   all        202         78      0.758       0.61      0.691      0.431      0.758       0.61      0.696      0.353

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     36/100      3.17G      1.386      1.726      1.185    0.01112     0.2482          9        640: 100% ━━━━━━━━━━━━ 59/59 7.9it/s 7.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 10.9it/s 0.6s.3s

{'box_precision': 0.8363833284662896,
 'box_recall': 0.7720490164948297,
 'box_map50': 0.8464394251042195,
 'box_map50_95': 0.5335586360601706,
 'seg_precision': 0.8621853535608359,
 'seg_recall': 0.6910998124446573,
 'seg_map50': 0.8188881898048079,
 'seg_map50_95': 0.46018367816984557}

## 9. Run the remaining baselines

In [19]:
# After Magnetic Tile succeeds:

baseline_results["KolektorSDD2"] = train_dataset("KolektorSDD2")

Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Laptop GPU, 7708MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=datasets/yolo_segmentation/KolektorSDD2/dataset.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=kolektorsdd2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs/segment, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    790431  ultralytics.nn.modules.head.Segment26        [1, 32, 64, 1, True, [64, 128, 256]]
YOLO26n-seg summary: 309 layers, 3,053,055 parameters, 3,053,055 gradients, 10.3 GFLOPs

Transferred 740/844 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4540.5±4141.2 MB/s, size: 250.3 KB)
train: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/KolektorSDD2/labels/train... 1982 images, 1776 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1982/1982 3.2Kit/s 0.6s0.0s
train: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/KolektorSDD2/labels/train.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 7109.9±4484.8 MB/s, size: 251.1 KB)
val: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/KolektorSDD2/labels/val... 350 images, 310 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 350/350 2.7Kit/s 0.1s<0.1s
val: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/KolektorSDD2/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 134 weight(decay=0.0), 154 weight(decay=0.0005), 154 bias(decay=0.0)
Plotting labels to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/labels.jpg...
MLflow: logging run_id(ffbe0b0fae594d55a932af714001db2a) to sqlite:///mlflow.db
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      1/100      3.22G      1.837      3.467      58.93   0.009526      2.532          2        640: 100% ━━━━━━━━━━━━ 124/124 6.9it/s 18.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 5.2it/s 2.1s<0.1s
                   all        350         43      0.332       0.22      0.207      0.067      0.324      0.233      0.176     0.0542

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      2/100      3.22G      1.958      3.311      27.67    0.01149     0.5503          1        640: 100% ━━━━━━━━━━━━ 124/124 7.9it/s 15.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 17.2it/s 0.6s0.1s
                   all        350         43      0.226      0.163      0.144     0.0346      0.408      0.288      0.296     0.0968

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      3/100      3.22G       2.44      3.421      11.34    0.01451     0.5545          2        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 17.8it/s 0.6s0.1s
                   all        350         43    0.00463      0.767     0.0538     0.0128    0.00463      0.767     0.0723      0.023

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      4/100      3.22G      2.414       3.21      5.076    0.01268     0.5034          4        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 17.3it/s 0.6s0.1s
                   all        350         43      0.145      0.174     0.0661     0.0225      0.186       0.14      0.137      0.027

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      5/100      3.22G      2.279      3.178      3.675    0.01313     0.4478          7        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.9it/s 0.6s0.1s
                   all        350         43       0.15       0.14      0.113      0.034      0.201      0.186      0.131     0.0417

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      6/100      3.22G      2.204      3.067      3.314    0.01251     0.4678          5        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.2it/s 0.6s0.1s
                   all        350         43      0.138      0.279      0.126     0.0331      0.205      0.395      0.186     0.0487

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      7/100      3.22G      2.232      3.168      3.079    0.01318     0.4492          2        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.6it/s 0.6s0.1s
                   all        350         43       0.15      0.116      0.128     0.0292      0.278      0.256      0.192     0.0423

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      8/100      3.22G      2.283      3.057      2.867    0.01407     0.5165          1        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.3it/s 0.6s0.1s
                   all        350         43       0.27      0.302      0.214     0.0752       0.27      0.302      0.214     0.0701

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      9/100      3.22G      2.072      2.804      2.595    0.01199     0.3689          3        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.0it/s 0.6s0.1s
                   all        350         43      0.248      0.279      0.183     0.0576      0.296      0.233      0.196     0.0593

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     10/100      3.22G       2.14      3.158      2.657    0.01139     0.4019          3        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.8it/s 0.6s0.1s
                   all        350         43      0.151      0.209      0.123     0.0373      0.208      0.302      0.162     0.0456

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     11/100      3.22G      2.147      3.055      2.556    0.01163      0.451          2        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.7it/s 0.6s0.1s
                   all        350         43      0.281      0.349      0.232     0.0647      0.247      0.442      0.212     0.0646

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     12/100      3.22G      2.174      2.828      2.512    0.01223     0.4476          2        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.3it/s 0.6s0.1s
                   all        350         43      0.185      0.372      0.159     0.0544      0.282      0.419      0.211     0.0686

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     13/100      3.22G      2.104      2.712      2.271     0.0122     0.3848          2        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.9it/s 0.6s0.1s
                   all        350         43      0.257      0.349      0.188     0.0736      0.267      0.419      0.257     0.0902

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     14/100      3.22G       2.08      2.862      2.338    0.01252     0.4355          0        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.8it/s 0.6s0.1s
                   all        350         43      0.398      0.279      0.297     0.0902      0.298      0.209      0.263     0.0865

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     15/100      3.22G      2.121      2.799      2.245    0.01303      0.375          6        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.5s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.4it/s 0.6s0.1s
                   all        350         43      0.203      0.326       0.19     0.0689      0.326      0.302      0.211     0.0749

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     16/100      3.22G      2.099      2.583      1.983    0.01114     0.4038          2        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.6it/s 0.6s0.1s
                   all        350         43      0.281      0.372       0.24     0.0667      0.311      0.372      0.246     0.0757

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     17/100      3.22G      2.124       2.71      2.122    0.01089     0.3564          3        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.4s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.2it/s 0.6s0.1s
                   all        350         43      0.271      0.328      0.237      0.088      0.322      0.372      0.293     0.0995

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     18/100      3.22G      2.009      2.625      2.064    0.01072     0.3915          6        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.8it/s 0.6s0.1s
                   all        350         43      0.259      0.256      0.156     0.0474      0.356      0.244      0.193     0.0613

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     19/100      3.22G      1.917      2.581      1.964    0.01039     0.3651          0        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 17.5it/s 0.6s0.1s
                   all        350         43      0.416      0.512      0.301      0.112      0.432      0.395      0.308     0.0982

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     20/100      3.22G      2.085      2.664      2.184     0.0107     0.4021          5        640: 100% ━━━━━━━━━━━━ 124/124 8.0it/s 15.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 17.8it/s 0.6s0.1s
                   all        350         43      0.308      0.467      0.252       0.09      0.293      0.443      0.255     0.0899

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     21/100      3.22G       2.08      2.579      2.089    0.01157     0.4578          3        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.2it/s 0.6s0.1s
                   all        350         43      0.412      0.419      0.372       0.12      0.453      0.425       0.35      0.108

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     22/100      3.22G      1.936      2.575      1.922     0.0103     0.3636          6        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.5it/s 0.6s0.1s
                   all        350         43      0.389      0.442      0.386      0.133      0.408      0.465      0.347      0.146

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     23/100      3.22G      1.964      2.509      1.954    0.01104      0.337          3        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 18.8it/s 0.6s0.1s
                   all        350         43      0.431      0.458      0.422      0.163      0.427       0.45      0.431      0.147

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     24/100      3.22G      1.929      2.649      1.921    0.01134     0.3892          2        640: 100% ━━━━━━━━━━━━ 124/124 8.2it/s 15.2s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 11/11 19.7it/s 0.6s.2s
                   all        350         43      0.474      0.465      0.467      0.222      0.499      0.488      0.505      0.233

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     25/100      3.22G      1.888      2.492      1.822   0.009993     0.3633          0        640: 100% ━━━━━━━━━━━━ 124/124 8.1it/s 15.3s0.2s

In [20]:
baseline_results["DAGM"] = train_dataset("DAGM")

Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Laptop GPU, 7708MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=datasets/yolo_segmentation/DAGM/dataset.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=dagm, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs/segment, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=10

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    794526  ultralytics.nn.modules.head.Segment26        [10, 32, 64, 1, True, [64, 128, 256]]
YOLO26n-seg summary: 309 layers, 3,057,150 parameters, 3,057,150 gradients, 10.3 GFLOPs

Transferred 740/844 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 914.9±264.2 MB/s, size: 195.2 KB)
train: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/DAGM/labels/train... 1725 images, 1478 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1725/1725 3.7Kit/s 0.5s0.1s
train: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/DAGM/labels/train.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 647.9±359.4 MB/s, size: 175.5 KB)
val: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/DAGM/labels/val... 911 images, 793 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 911/911 2.5Kit/s 0.4s0.1ss
val: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/DAGM/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 134 weight(decay=0.0), 154 weight(decay=0.0005), 154 bias(decay=0.0)
Plotting labels to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/labels.jpg...
MLflow: logging run_id(8bb98d16aecc461e937bd2b7bcd4df8a) to sqlite:///mlflow.db
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      1/100      3.27G      1.961      3.989      56.93    0.02139      7.841          3        640: 100% ━━━━━━━━━━━━ 108/108 6.8it/s 15.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 6.6it/s 4.4s0.1s
                   all        911        118      0.544      0.172      0.144     0.0845      0.531      0.116     0.0812      0.033

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      2/100      3.77G      1.658      2.916      44.63     0.0158      3.902          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 7.4it/s 3.9s0.1s
                   all        911        118      0.942     0.0706     0.0804     0.0311      0.946     0.0765     0.0772     0.0279

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      3/100      3.12G      1.698      2.817      30.19     0.0162      2.749          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.2it/s 3.5s0.1s
                   all        911        118      0.876     0.0965     0.0813     0.0252      0.863     0.0926     0.0802     0.0234

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      4/100      3.12G      1.743      2.812      16.94    0.01844      1.788          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.3it/s 3.5s0.1s
                   all        911        118      0.141      0.103      0.048     0.0201      0.137     0.0978     0.0396     0.0188

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      5/100      3.12G      1.708      2.363      11.64    0.01867     0.7707          3        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118     0.0482      0.104     0.0606     0.0235     0.0322     0.0993      0.048     0.0234

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      6/100      3.12G      1.758      2.456      7.904    0.01914     0.1776          3        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118     0.0534      0.113     0.0739     0.0377     0.0669      0.126     0.0816     0.0358

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      7/100      3.12G      1.833      2.585      6.168    0.01847    0.06775          5        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.291     0.0647      0.116     0.0488      0.188     0.0956      0.158     0.0557

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      8/100      3.12G        1.7      2.331      4.529    0.01813     0.0651          4        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.159      0.114      0.141     0.0636       0.17      0.127      0.156     0.0601

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
      9/100      3.12G      1.697      2.304      3.574     0.0172    0.05121          3        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118     0.0781      0.184      0.121      0.061      0.118      0.205      0.175     0.0847

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     10/100      3.12G      1.591      2.209      3.059    0.01593    0.04737          3        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.172      0.129      0.177     0.0791      0.172      0.129      0.177     0.0721

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     11/100      3.13G      1.667       2.02      2.628    0.01798    0.04872          3        640: 100% ━━━━━━━━━━━━ 108/108 7.8it/s 13.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.4it/s 3.5s0.1s
                   all        911        118      0.252      0.236      0.239      0.117      0.245      0.238       0.24      0.116

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     12/100      3.13G      1.568      2.093      2.408    0.01508    0.04888          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.911      0.121      0.243      0.135      0.911      0.121      0.245      0.131

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     13/100      3.13G      1.578      2.105      2.422    0.01553    0.04265          6        640: 100% ━━━━━━━━━━━━ 108/108 8.0it/s 13.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.846       0.18      0.203      0.109      0.856       0.19       0.22      0.104

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     14/100      3.13G      1.547      2.039      2.186    0.01623    0.04158          6        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.844      0.193        0.2        0.1      0.852      0.205      0.212      0.103

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     15/100      3.13G      1.594       1.92      2.032    0.01668    0.04472          3        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.4it/s 3.4s0.1s
                   all        911        118      0.868      0.193      0.231      0.124      0.868      0.193      0.229      0.111

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     16/100      3.13G      1.567      1.847      1.772    0.01591     0.0379          7        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.862      0.234      0.234      0.133       0.86      0.238      0.237      0.124

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     17/100      3.13G      1.484      1.939      1.614    0.01535    0.03666          4        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.688      0.234      0.244      0.135      0.688      0.234      0.249      0.146

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     18/100      3.13G      1.502      1.919       1.59    0.01446     0.0398          5        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.885      0.234      0.259      0.124      0.882      0.228      0.246      0.127

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     19/100      3.13G       1.55      1.913       1.54    0.01462    0.03843          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.895      0.222      0.253      0.141      0.895      0.222      0.263      0.144

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     20/100      3.13G      1.521      1.871      1.509    0.01508    0.03631          4        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.727      0.228      0.249      0.136      0.735      0.234      0.269      0.133

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     21/100      3.13G      1.513       1.87        1.4    0.01449    0.03462          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.787      0.204      0.266      0.142      0.787      0.204      0.266      0.148

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     22/100      3.13G      1.551      1.758      1.349    0.01629    0.03491          5        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.784      0.233      0.249      0.142      0.784      0.233      0.249       0.13

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     23/100      3.13G      1.607      2.128      1.532    0.01424    0.03666          7        640: 100% ━━━━━━━━━━━━ 108/108 7.8it/s 13.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.5it/s 3.4s0.1s
                   all        911        118      0.818      0.223      0.265      0.154      0.818      0.223      0.266      0.142

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     24/100      3.13G       1.42      1.672      1.275    0.01377    0.03269          2        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.6s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s
                   all        911        118      0.705      0.234      0.274      0.161      0.722       0.24      0.295      0.161

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss    l1_loss   sem_loss  Instances       Size
     25/100      3.13G      1.465      1.881      1.292     0.0141    0.03716          4        640: 100% ━━━━━━━━━━━━ 108/108 7.9it/s 13.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 8.6it/s 3.4s0.1s

## 10. Held-out test evaluation

Run this only after selecting the best checkpoint from validation.

The test set is evaluated once for the final baseline report.

In [ ]:
def evaluate_test(dataset_name, best_model_path):
    yaml_path = DATASETS[dataset_name]

    experiment = mlflow.get_experiment_by_name(
        f"{PROJECT_NAME}_{dataset_name}"
    )

    with mlflow.start_run(
        experiment_id=experiment.experiment_id,
        run_name=f"{dataset_name}_test_evaluation",
    ):
        mlflow.log_params({
            "dataset": dataset_name,
            "split": "test",
            "model": str(best_model_path),
        })

        model = YOLO(best_model_path)

        metrics = model.val(
            data=str(yaml_path),
            split="test",
            imgsz=IMAGE_SIZE,
            batch=BATCH_SIZE,
            device=DEVICE,
            plots=True,
        )

        test_metrics = extract_metrics(metrics)

        if test_metrics:
            mlflow.log_metrics({
                f"test_{k}": v for k, v in test_metrics.items()
                if v is not None
            })

        mlflow.set_tags({
            "project": PROJECT_NAME,
            "dataset": dataset_name,
            "task": "instance_segmentation",
            "stage": "test_evaluation",
        })

        return test_metrics

In [22]:

# Example:
test_metrics = evaluate_test(
    "Magnetic_Tile",
    baseline_results["Magnetic_Tile"]["best_model"],
)
test_metrics

Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5070 Laptop GPU, 7708MiB)
YOLO26n-seg summary (fused): 139 layers, 2,689,859 parameters, 0 gradients, 9.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 192.3±61.2 MB/s, size: 21.7 KB)
val: Scanning /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile/labels/test... 202 images, 144 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 202/202 5.1Kit/s 0.0s
val: New cache created: /home/zubair/AI Development Directory/anomaly-detection/datasets/yolo_segmentation/Magnetic_Tile/labels/test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 13/13 7.0it/s 1.9s<0.1s
                   all        202         69      0.896      0.717      0.849       0.57       0.74      0.811       0.83      0.461
              Blowhole         17         17      0.969          1      0.995      0.586      0.807          1      0.995      0.471
                 Break         13         21      0.922      0.524      0.739      0.432      0.756       0.59      0.643      0.278
                 Crack          9         10          1      0.576      0.888      0.639      0.722        0.9      0.888      0.354
                  Fray          5          7      0.747      0.845      0.797      0.583      0.583      0.857      0.797      0.609
                Uneven         14         14      0.843      0.643      0.826      0.608      0.832       0.71      0.826      0.591
Speed: 0.5ms preprocess, 1.9ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/val-4

{'box_precision': 0.8961672002012113,
 'box_recall': 0.7174882856470528,
 'box_map50': 0.8489513613579405,
 'box_map50_95': 0.569656524108495,
 'seg_precision': 0.7400502482090943,
 'seg_recall': 0.8112925131881956,
 'seg_map50': 0.8296373168884779,
 'seg_map50_95': 0.4608649352595569}

## 11. Qualitative prediction inspection

Industrial inspection should not be judged by mAP alone.

Inspect:

- normal images → no false detections
- tiny defects
- low-contrast defects
- irregular defects
- multiple disconnected defects
- difficult DAGM classes, especially Classes 7–10

In [34]:
def predict_samples(dataset_name, model_path, split="test", n=6, conf=0.25):
    root = dataset_info[dataset_name]["root"]
    image_dir = root / "images" / split

    images = sorted([
        p for p in image_dir.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    ])[:n]

    model = YOLO(model_path)

    results = model.predict(
        source=[str(p) for p in images],
        conf=conf,
        imgsz=IMAGE_SIZE,
        device=DEVICE,
        save=True,
        project=str(RUNS_DIR / "predictions"),
        name=dataset_name.lower(),
        exist_ok=True,
    )

    print("Predictions:", RUNS_DIR / "predictions" / dataset_name.lower())
    return results

# Example:
# predict_samples(
#     "Magnetic_Tile",
#     baseline_results["Magnetic_Tile"]["best_model"],
#     split="test",
# )

# predict_samples(
#     "DAGM",
#     baseline_results["DAGM"]["best_model"],
#     split="test",
# )

predict_samples(
    "KolektorSDD2",
    baseline_results["KolektorSDD2"]["best_model"],
    split="test",
)

0: 640x640 (no detections), 1.9ms
1: 640x640 (no detections), 1.9ms
2: 640x640 (no detections), 1.9ms
3: 640x640 (no detections), 1.9ms
4: 640x640 (no detections), 1.9ms
5: 640x640 (no detections), 1.9ms
Speed: 0.7ms preprocess, 1.9ms inference, 0.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2
Predictions: runs/segment/predictions/kolektorsdd2

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'defect'}
 obb: None
 orig_img: array([[[42, 29, 24],
         [38, 30, 32],
         [47, 38, 40],
         ...,
         [47, 41, 43],
         [41, 40, 38],
         [45, 46, 54]],

        [[27, 24, 23],
         [26, 21, 23],
         [32, 29, 30],
         ...,
         [41, 40, 41],
         [47, 46, 45],
         [42, 49, 53]],

        [[22, 16, 16],
         [20, 18, 19],
         [27, 24, 26],
         ...,
         [38, 41, 45],
         [46, 52, 54],
         [51, 51, 62]],

        ...,

        [[ 3,  6,  7],
         [17, 17, 22],
         [40, 38, 42],
         ...,
         [39, 39, 37],
         [37, 31, 32],
         [36, 32, 33]],

        [[ 6,  6,  5],
         [13, 11, 13],
         [27, 26, 28],
         ...,
         [42, 40, 40],
         [32, 32, 33],
         [37, 36, 32]],

        [[ 3,  5,  5],
         [11,  9,  8],
         [17, 17, 22],
         ...,
         [44, 41, 44],
         [39, 39, 40],
         [45, 45, 44]]], shape=(636, 231, 3), dtype=uint8)
 orig_shape: (636, 231)
 path: 'image0.jpg'
 probs: None
 save_dir: '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2'
 semantic_mask: None
 speed: {'preprocess': 0.6877860002229378, 'inference': 1.9267884999862872, 'postprocess': 0.07187333297527705},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'defect'}
 obb: None
 orig_img: array([[[22, 18, 16],
         [23, 23, 22],
         [27, 26, 24],
         ...,
         [52, 51, 59],
         [46, 55, 65],
         [54, 55, 55]],

        [[18, 18, 18],
         [26, 24, 28],
         [31, 26, 22],
         ...,
         [53, 53, 53],
         [58, 60, 66],
         [48, 51, 54]],

        [[23, 22, 23],
         [29, 24, 30],
         [31, 27, 21],
         ...,
         [52, 55, 55],
         [53, 49, 53],
         [41, 41, 45]],

        ...,

        [[34, 28, 27],
         [27, 22, 23],
         [18, 19, 18],
         ...,
         [41, 38, 40],
         [35, 31, 26],
         [35, 30, 30]],

        [[26, 21, 18],
         [20, 18, 15],
         [16, 18, 19],
         ...,
         [30, 23, 26],
         [32, 35, 38],
         [34, 34, 32]],

        [[31, 25, 21],
         [23, 22, 18],
         [26, 23, 16],
         ...,
         [28, 27, 26],
         [35, 36, 44],
         [41, 47, 49]]], shape=(642, 231, 3), dtype=uint8)
 orig_shape: (642, 231)
 path: 'image1.jpg'
 probs: None
 save_dir: '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2'
 semantic_mask: None
 speed: {'preprocess': 0.6877860002229378, 'inference': 1.9267884999862872, 'postprocess': 0.07187333297527705},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'defect'}
 obb: None
 orig_img: array([[[27, 20, 20],
         [30, 28, 30],
         [37, 32, 27],
         ...,
         [48, 43, 44],
         [49, 46, 44],
         [50, 46, 46]],

        [[28, 26, 20],
         [28, 27, 29],
         [34, 30, 26],
         ...,
         [48, 43, 48],
         [51, 49, 44],
         [54, 50, 52]],

        [[24, 24, 24],
         [32, 28, 30],
         [40, 37, 29],
         ...,
         [53, 48, 46],
         [57, 58, 50],
         [55, 50, 45]],

        ...,

        [[ 2,  3,  3],
         [10,  9, 10],
         [18, 14, 12],
         ...,
         [49, 44, 43],
         [46, 40, 51],
         [51, 44, 50]],

        [[ 2,  3,  2],
         [ 8,  7,  9],
         [10, 10,  9],
         ...,
         [48, 42, 35],
         [37, 38, 40],
         [38, 40, 39]],

        [[ 2,  3,  3],
         [ 4,  6,  6],
         [10,  9,  7],
         ...,
         [44, 44, 47],
         [47, 40, 36],
         [48, 45, 46]]], shape=(631, 231, 3), dtype=uint8)
 orig_shape: (631, 231)
 path: 'image2.jpg'
 probs: None
 save_dir: '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2'
 semantic_mask: None
 speed: {'preprocess': 0.6877860002229378, 'inference': 1.9267884999862872, 'postprocess': 0.07187333297527705},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'defect'}
 obb: None
 orig_img: array([[[61, 54, 43],
         [38, 32, 19],
         [18, 14, 11],
         ...,
         [38, 43, 45],
         [46, 44, 40],
         [48, 46, 47]],

        [[52, 37, 40],
         [28, 26, 21],
         [22, 18, 13],
         ...,
         [37, 34, 46],
         [52, 47, 43],
         [44, 45, 48]],

        [[30, 26, 22],
         [30, 27, 27],
         [30, 24, 24],
         ...,
         [34, 34, 36],
         [45, 43, 44],
         [42, 42, 41]],

        ...,

        [[29, 31, 37],
         [36, 33, 32],
         [33, 28, 31],
         ...,
         [28, 30, 30],
         [40, 41, 35],
         [42, 43, 44]],

        [[22, 17, 22],
         [29, 23, 22],
         [30, 33, 30],
         ...,
         [37, 35, 38],
         [49, 48, 46],
         [56, 56, 55]],

        [[18, 15, 15],
         [21, 19, 20],
         [29, 34, 41],
         ...,
         [40, 41, 48],
         [44, 43, 45],
         [53, 54, 58]]], shape=(636, 229, 3), dtype=uint8)
 orig_shape: (636, 229)
 path: 'image3.jpg'
 probs: None
 save_dir: '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2'
 semantic_mask: None
 speed: {'preprocess': 0.6877860002229378, 'inference': 1.9267884999862872, 'postprocess': 0.07187333297527705},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'defect'}
 obb: None
 orig_img: array([[[27, 22, 22],
         [33, 26, 29],
         [25, 23, 22],
         ...,
         [38, 40, 50],
         [49, 45, 40],
         [39, 40, 45]],

        [[30, 26, 26],
         [33, 28, 29],
         [28, 26, 23],
         ...,
         [41, 40, 43],
         [44, 44, 42],
         [43, 43, 46]],

        [[34, 30, 35],
         [34, 35, 34],
         [27, 26, 23],
         ...,
         [49, 44, 49],
         [49, 48, 49],
         [53, 55, 58]],

        ...,

        [[42, 43, 38],
         [35, 32, 22],
         [30, 28, 34],
         ...,
         [40, 33, 34],
         [43, 38, 39],
         [44, 41, 45]],

        [[53, 53, 48],
         [53, 45, 38],
         [37, 30, 31],
         ...,
         [40, 32, 26],
         [35, 33, 38],
         [42, 36, 36]],

        [[47, 43, 47],
         [43, 35, 37],
         [39, 36, 31],
         ...,
         [41, 36, 28],
         [29, 28, 29],
         [43, 40, 42]]], shape=(632, 230, 3), dtype=uint8)
 orig_shape: (632, 230)
 path: 'image4.jpg'
 probs: None
 save_dir: '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2'
 semantic_mask: None
 speed: {'preprocess': 0.6877860002229378, 'inference': 1.9267884999862872, 'postprocess': 0.07187333297527705},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'defect'}
 obb: None
 orig_img: array([[[33, 27, 32],
         [32, 29, 29],
         [31, 30, 32],
         ...,
         [29, 26, 26],
         [29, 28, 27],
         [31, 29, 26]],

        [[26, 26, 24],
         [33, 28, 26],
         [30, 27, 26],
         ...,
         [38, 35, 29],
         [31, 27, 28],
         [28, 28, 27]],

        [[28, 25, 24],
         [29, 24, 21],
         [28, 28, 27],
         ...,
         [67, 54, 45],
         [37, 37, 32],
         [33, 30, 29]],

        ...,

        [[21, 26, 29],
         [39, 32, 26],
         [32, 24, 20],
         ...,
         [40, 35, 38],
         [43, 38, 41],
         [39, 34, 31]],

        [[19, 21, 30],
         [43, 36, 33],
         [39, 30, 27],
         ...,
         [34, 34, 36],
         [41, 35, 37],
         [32, 30, 27]],

        [[12, 12, 13],
         [27, 24, 27],
         [33, 26, 27],
         ...,
         [39, 32, 41],
         [37, 33, 35],
         [36, 33, 34]]], shape=(638, 229, 3), dtype=uint8)
 orig_shape: (638, 229)
 path: 'image5.jpg'
 probs: None
 save_dir: '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/predictions/kolektorsdd2'
 semantic_mask: None
 speed: {'preprocess': 0.6877860002229378, 'inference': 1.9267884999862872, 'postprocess': 0.07187333297527705}]

## 12. Baseline comparison

Use the segmentation metrics as the primary model-selection metrics:

- **Segmentation mAP50**
- **Segmentation mAP50-95**
- Precision
- Recall
- Training time

Do not interpret the three datasets as one homogeneous benchmark. They have different domains, defect types and difficulty.

In [ ]:
# Fill from the completed MLflow runs after test evaluation.

comparison = pd.DataFrame([
    {
        "dataset": "DAGM",
        "seg_mAP50": ...,
        "seg_mAP50_95": ...,
        "precision": ...,
        "recall": ...,
        "training_seconds": ...,
    },
    {
        "dataset": "KolektorSDD2",
        "seg_mAP50": ...,
        "seg_mAP50_95": ...,
        "precision": ...,
        "recall": ...,
        "training_seconds": ...,
    },
    {
        "dataset": "Magnetic_Tile",
        "seg_mAP50": ...,
        "seg_mAP50_95": ...,
        "precision": ...,
        "recall": ...,
        "training_seconds": ...,
    },
])

display(comparison)

         dataset seg_mAP50 seg_mAP50_95 precision    recall training_seconds
0           DAGM  Ellipsis     Ellipsis  Ellipsis  Ellipsis         Ellipsis
1   KolektorSDD2  Ellipsis     Ellipsis  Ellipsis  Ellipsis         Ellipsis
2  Magnetic_Tile  Ellipsis     Ellipsis  Ellipsis  Ellipsis         Ellipsis

:

In [22]:
from ultralytics import YOLO
from pathlib import Path

BASE_RUNS_DIR = Path("/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment")
# output_dir = Path("/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment")??/


import shutil
from pathlib import Path
from ultralytics import YOLO

def export_yolo_model_to_onnx(best_model_path, output_dir):
    model = YOLO(best_model_path)
    
    # 1. Export (Ultralytics returns the file path of the generated ONNX model)
    exported_path_str = model.export(format="onnx", dynamic=True, simplify=True)
    exported_file = Path(exported_path_str)
    
    # 2. Move or rename to your desired target destination
    target_path = Path(output_dir) / exported_file.name
    target_path.parent.mkdir(parents=True, exist_ok=True)
    
    shutil.move(exported_file, target_path)
    print(f"Model successfully saved to {target_path}")

In [23]:
# export the best models for each dataset to ONNX format, path to best models in BASE_RUNS_DIR
for dataset_name in ["dagm", "kolektorsdd2", "magnetic_tile"]:
    best_model_path = BASE_RUNS_DIR / dataset_name.lower() / "weights" / "best.pt"
    output_dir = BASE_RUNS_DIR / dataset_name.lower() / "onnx_models"
    export_yolo_model_to_onnx(best_model_path, output_dir)

Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CPU (AMD Ryzen AI 9 365 w/ Radeon 880M)
YOLO26n-seg summary (fused): 139 layers, 2,690,834 parameters, 0 gradients, 9.1 GFLOPs

PyTorch: starting from '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 300, 38), (1, 32, 160, 160)) (6.3 MB)

ONNX: starting export with onnx 1.22.0 opset 20...
ONNX: slimming with onnxslim 0.1.96...
ONNX: export success ✅ 2.0s, saved as '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/weights/best.onnx' (10.9 MB)

Export complete (2.2s)
Results saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/weights/best.onnx
Predict:         yolo predict task=segment model=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/weights/best.onnx imgsz=640
Validate:        yolo val task=segment model=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/weights/best.onnx imgsz=640 data=datasets/yolo_segmentation/DAGM/dataset.yaml
Visualize:       https://netron.app
Model successfully saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/dagm/onnx_models/best.onnx
Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CPU (AMD Ryzen AI 9 365 w/ Radeon 880M)
YOLO26n-seg summary (fused): 139 layers, 2,689,079 parameters, 0 gradients, 9.1 GFLOPs

PyTorch: starting from '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 300, 38), (1, 32, 160, 160)) (6.2 MB)

ONNX: starting export with onnx 1.22.0 opset 20...
ONNX: slimming with onnxslim 0.1.96...
ONNX: export success ✅ 1.6s, saved as '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/weights/best.onnx' (10.9 MB)

Export complete (1.8s)
Results saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/weights/best.onnx
Predict:         yolo predict task=segment model=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/weights/best.onnx imgsz=640
Validate:        yolo val task=segment model=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/weights/best.onnx imgsz=640 data=datasets/yolo_segmentation/KolektorSDD2/dataset.yaml
Visualize:       https://netron.app
Model successfully saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/kolektorsdd2/onnx_models/best.onnx
Ultralytics 8.4.117 🚀 Python-3.14.4 torch-2.13.0+cu130 CPU (AMD Ryzen AI 9 365 w/ Radeon 880M)
YOLO26n-seg summary (fused): 139 layers, 2,689,859 parameters, 0 gradients, 9.1 GFLOPs

PyTorch: starting from '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 300, 38), (1, 32, 160, 160)) (6.2 MB)

ONNX: starting export with onnx 1.22.0 opset 20...
ONNX: slimming with onnxslim 0.1.96...
ONNX: export success ✅ 1.7s, saved as '/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/weights/best.onnx' (10.9 MB)

Export complete (1.9s)
Results saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/weights/best.onnx
Predict:         yolo predict task=segment model=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/weights/best.onnx imgsz=640
Validate:        yolo val task=segment model=/home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/weights/best.onnx imgsz=640 data=datasets/yolo_segmentation/Magnetic_Tile/dataset.yaml
Visualize:       https://netron.app
Model successfully saved to /home/zubair/AI Development Directory/anomaly-detection/runs/segment/runs/segment/magnetic_tile/onnx_models/best.onnx

# Expected output

```text
VisionInspect/
├── datasets/
│   └── yolo_segmentation/
│
├── runs/
│   └── segment/
│       ├── magnetic_tile/
│       ├── kolektorsdd2/
│       ├── dagm/
│       └── predictions/
│
├── mlruns/
│
└── notebooks/
    ├── 01_dataset_analysis.ipynb
    ├── 02_prepare_yolo_segmentation.ipynb
    └── 03_train_yolo_segmentation.ipynb
```

### Next stage

After the baselines are stable:

```text
YOLO Segmentation
       │
       ├── PyTorch checkpoint
       │
       └── ONNX
             │
             ├── FastAPI inference service
             │
             └── Streamlit inspection UI
```

Triton comes later, after ONNX inference is working and benchmarked. It is an optimization/serving component, not a prerequisite for establishing the baseline.